### ISSUE TITLE
CUDA compilation issue for camfer distance

### ISSUE THREAD

**Issue by nicolas-chaulet** [nicolas-chaulet/torch-points-kernels#50]
https://github.com/nicolas-chaulet/torch-points3d/issues/349

**Comment by CCInc** [comment]
Looks like atomicAdd for doubles is only implemented on cuda >=6.0, which shouldn't be too big of an issue because most relatively recent GPUs will work with it.

To get the training dockerfile in torch-points3d to compile, I had to remove support for architectures under 6.0.

To support older gpus maybe some sort of wrapper like [this](https://stackoverflow.com/a/39287554/1482644) will get the job done? not sure how good that implementation is
